name: Demo-CCO
on:
  workflow_dispatch:

env:
  ENV_NAME: "demo CCO"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
    # Checkout Code
    - uses: actions/checkout@v2
    
    - run: echo Hello World!
